# Generated by Django 4.2.7 on 2023-12-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="filter_product_type",
            field=models.ManyToManyField(
                blank=True,
                to="products.producttype",
                verbose_name="Filter Product Type ID",
            ),
        ),
    ]
