# Generated by Django 4.2.8 on 2023-12-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_invoices', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirminvoiceheader',
            options={'ordering': ('inv_status', 'inv_no', 'updated_at'), 'permissions': [('is_download_report', 'ดูรายงาน'), ('edit_qty', 'แก้ไขจำนวน'), ('print_tag', 'Print TAG')], 'verbose_name': 'Confirm Invoice', 'verbose_name_plural': 'EDI Confirm Invoice'},
        ),
    ]
