# Generated by Django 4.2.8 on 2023-12-19 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confirm_invoices', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='PRIMARY KEY')),
                ('purchase_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='PO No.')),
                ('receive_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Receive No.')),
                ('receive_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('inv_delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('inv_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Invoice No.')),
                ('item', models.IntegerField(verbose_name='Item')),
                ('qty', models.IntegerField(verbose_name='Qty')),
                ('summary_price', models.FloatField(blank=True, default='0', null=True, verbose_name='Summary Price')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('receive_status', models.CharField(blank=True, choices=[('0', 'กำลังดำเนินงาน'), ('1', 'รับเข้าแล้ว'), ('2', 'ยกเลิกแล้ว')], default='0', max_length=1, null=True, verbose_name='Receive Status')),
                ('ref_formula_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='Formula ID')),
                ('is_download_count', models.IntegerField(blank=True, default='0', null=True, verbose_name='Download Count')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirm_invoice_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='confirm_invoices.confirminvoiceheader', verbose_name='PO No.')),
                ('part_model_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productgroup', verbose_name='Model ID')),
                ('receive_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Receive By ID')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.supplier', verbose_name='Supplier ID')),
            ],
            options={
                'verbose_name': 'Receive',
                'verbose_name_plural': 'EDI Receive Invoice',
                'db_table': 'ediReceiveHeader',
            },
        ),
        migrations.CreateModel(
            name='ReceiveDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='PRIMARY KEY')),
                ('seq', models.IntegerField(verbose_name='Seq')),
                ('qty', models.IntegerField(verbose_name='Qty')),
                ('summary_price', models.FloatField(blank=True, default='0', null=True, verbose_name='Summary Price')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('receive_status', models.CharField(blank=True, choices=[('0', 'กำลังดำเนินงาน'), ('1', 'รับเข้าแล้ว'), ('2', 'ยกเลิกแล้ว')], default='0', max_length=1, null=True, verbose_name='Receive Status')),
                ('ref_formula_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='Formula ID')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirm_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confirm_invoices.confirminvoicedetail', verbose_name='Confirm Detail')),
                ('receive_header_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='receives.receiveheader', verbose_name='Receive ID')),
            ],
            options={
                'verbose_name': 'Receive Detail',
                'verbose_name_plural': 'Receive Detail',
                'db_table': 'ediReceiveDetail',
                'ordering': ['seq'],
            },
        ),
    ]
