# Generated by Django 4.2.8 on 2023-12-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_pds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdsheader',
            options={'ordering': ('pds_status', 'pds_no', 'created_at', 'updated_at'), 'permissions': [('create_purchase_order', 'เปิด PO'), ('is_download_report', 'ดูรายงาน'), ('add_new_item', 'เพิ่มรายการใหม่'), ('edit_qty', 'แก้ไขจำนวน'), ('edit_price', 'แก้ไขราคา'), ('print_tag', 'Print TAG')], 'verbose_name': 'PDS', 'verbose_name_plural': 'Open PDS'},
        ),
        migrations.AlterField(
            model_name='pdsdetail',
            name='pds_detail_status',
            field=models.CharField(blank=True, choices=[(0, 'รอเปิด PDS'), (1, 'เปิด PDS บางส่วน'), (2, 'เสร็จสมบูรณ์'), (3, 'ยกเลิก'), (4, 'ถูกยกเลิก PDS')], default='0', max_length=1, null=True, verbose_name='PDS Status'),
        ),
        migrations.AlterField(
            model_name='pdsheader',
            name='pds_status',
            field=models.CharField(blank=True, choices=[(0, 'รอเปิด PDS'), (1, 'เปิด PDS บางส่วน'), (2, 'เสร็จสมบูรณ์'), (3, 'ยกเลิก'), (4, 'ถูกยกเลิก PDS')], default='0', max_length=1, null=True, verbose_name='PDS Status'),
        ),
    ]
