# Generated by Django 4.2.8 on 2023-12-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_pds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdsheader',
            name='pds_status',
            field=models.CharField(blank=True, choices=[(0, 'รอเปิด PDS'), (1, 'เปิด PDS บางส่วน'), (2, 'เสร็จสมบูรณ์'), (3, 'ยกเลิก'), (4, '-')], default='0', max_length=1, null=True, verbose_name='PDS Status'),
        ),
    ]
