# Generated by Django 5.0 on 2023-12-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementuser',
            name='supplier_id',
            field=models.ManyToManyField(blank=True, related_name='SetSupplier', to='members.supplier', verbose_name='Supplier ID'),
        ),
    ]
