# Generated by Django 4.2.7 on 2023-12-14 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_managementuser_supplier_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="JasperReportServer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="PRIMARY KEY",
                    ),
                ),
                (
                    "server_name",
                    models.CharField(max_length=255, verbose_name="Server Name"),
                ),
                (
                    "server_url",
                    models.CharField(max_length=255, verbose_name="Server URL"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Server Report PDS",
                "verbose_name_plural": "Server Report PDS",
                "db_table": "tbmServerReport",
            },
        ),
    ]
