# Generated by Django 4.2.8 on 2023-12-15 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_jasperreportserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='PRIMARY KEY')),
                ('remark', models.TextField(verbose_name='หมายเหตุ')),
                ('is_status', models.BooleanField(default=False, verbose_name='Is Error/Success')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Logging Report PDS',
                'verbose_name_plural': 'Logging Report PDS',
                'db_table': 'tbmLoggingReport',
            },
        ),
    ]
