# Generated by Django 4.2.8 on 2023-12-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_usererrorlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usererrorlog',
            options={'ordering': ('updated_on',), 'verbose_name': 'Logging Report Handle', 'verbose_name_plural': 'Logging Report Handle'},
        ),
        migrations.AlterField(
            model_name='usererrorlog',
            name='is_status',
            field=models.BooleanField(default=False, verbose_name='Success'),
        ),
    ]
